// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Projekat_V2.Migrations
{
    [DbContext(typeof(PostaContext))]
    [Migration("20220216192217_V3")]
    partial class V3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Paket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Datum_prijema")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Datum_slanja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Lomljivo")
                        .HasColumnType("bit");

                    b.Property<float>("Masa")
                        .HasColumnType("real");

                    b.Property<string>("Odrediste")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Posiljalac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PostaID")
                        .HasColumnType("int");

                    b.Property<string>("Primalac")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Primljen")
                        .HasColumnType("bit");

                    b.Property<int?>("VoziloID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PostaID");

                    b.HasIndex("VoziloID");

                    b.ToTable("Paket");
                });

            modelBuilder.Entity("Models.Posta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float>("Maks_kapacitet")
                        .HasColumnType("real");

                    b.Property<int>("Postanski_broj")
                        .HasColumnType("int");

                    b.Property<float>("Tr_kapacitet")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Posta");
                });

            modelBuilder.Entity("Models.Postar", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PostaID")
                        .HasColumnType("int");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("VoziloFK")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PostaID");

                    b.HasIndex("VoziloFK")
                        .IsUnique();

                    b.ToTable("Postar");
                });

            modelBuilder.Entity("Models.Vozilo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<float>("Max_kapacitet")
                        .HasColumnType("real");

                    b.Property<string>("Tablice")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<float>("Tr_kapacitet")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.ToTable("Vozilo");
                });

            modelBuilder.Entity("Models.Paket", b =>
                {
                    b.HasOne("Models.Posta", "Posta")
                        .WithMany("Paketi")
                        .HasForeignKey("PostaID");

                    b.HasOne("Models.Vozilo", "Vozilo")
                        .WithMany("Paketi")
                        .HasForeignKey("VoziloID");

                    b.Navigation("Posta");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("Models.Postar", b =>
                {
                    b.HasOne("Models.Posta", "Posta")
                        .WithMany("Postari")
                        .HasForeignKey("PostaID");

                    b.HasOne("Models.Vozilo", "Vozilo")
                        .WithOne("Postar")
                        .HasForeignKey("Models.Postar", "VoziloFK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Posta");

                    b.Navigation("Vozilo");
                });

            modelBuilder.Entity("Models.Posta", b =>
                {
                    b.Navigation("Paketi");

                    b.Navigation("Postari");
                });

            modelBuilder.Entity("Models.Vozilo", b =>
                {
                    b.Navigation("Paketi");

                    b.Navigation("Postar");
                });
#pragma warning restore 612, 618
        }
    }
}
